
backbone_arch: "ternaryvitbase"
agg_arch: "boq"
image_size: [322, 322]
pretrain_checkpoint: "/path/to/pretrained/checkpoint"

test_set_names: ["svox_night"]

test_dataset_dir: "/home/oliver/datasets_drive/vpr_datasets"
num_workers: 12
batch_size: 32
k_values: [1, 5, 10]
matching_precision: "float32"



